### ISSUE TITLE
fix(reducer): detect return type of each reducer [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#100]
## fix(reducer): detect return type of each reducer [3]

We should always specify return type when we create a reducer, example just below.

```
    [ELifeAction.RESOLVE_GET_LIFE]: (state, action): NLife.IState => ({
      ...state,
      ...action.payload,
    }),
```

## Tasks:

- [x] Check on each reducer if return type is specified
- [x] Update unit test
- [ ] Create action with `createAsyncAction`
- [x] Handle this action on `epic` middleware
- [ ] If it's success dispatch an `action.success`
- [ ] If there is an error dispatch an `action.failure`
- [ ] On the reducer, handle three cases: `success`, `failure`, `cancel` (optional)

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://redux.js.org/basics/reducers
- https://github.com/piotrwitek/typesafe-actions#createreducer

## Related issues

N/A
