### ISSUE TITLE
feat(venues): handle error case on venues epic [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#119]
## feat(venues): handle error case on venues epic [2]

If there is no internet connection, every epic should handle error case.

Example:

```
      from(new Promise(...)).pipe(
        map(myAction.success),
        catchError(pipe(myAction.failure, of)),
        takeUntil(action$.pipe(filter(isActionOf(myAction.cancel)))),
      )
```

## Tasks:

- [x] Use created async action
- [x] Handle error case
- [x] Handle cancel case
- [x] Store the status of the last request in store

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://github.com/piotrwitek/typesafe-actions

## Related issues

#120
