### ISSUE TITLE
feat(status): add status module [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#140]
## Add status module

The idea is to store every action status.

## Tasks:

- [ ] Define a new type for status `NStatus`
- [ ] Create a store `statusReducer`
- [ ] Handle every async `action`
- [ ] Update `isLoading` if needed
- [ ] Update `hasError` if neeede
- [ ] Create selector

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

N/A
