### ISSUE TITLE
feat(venue-explore): create an epic venue explore [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#157]
## feat(venue-explore): create an epic venue explore

N/A

## Tasks:

- [ ] Udapte `EApiPathnames`, add endpoint for venue explore
- [ ] Create an epic `getVenuesExploreEpic`
- [ ] Use `adaptGetVenuesSearch` on service callback
- [ ] On error case, dispatch `EVenuesAction.GET_VENUE_EXPLORE_FAILURE`
- [ ] On multiple call, dispatch `EVenuesAction.GET_VENUE_EXPLORE_CANCEL`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

#156
#159
#158
