### ISSUE TITLE
feat(venue-explore): create a service for venue explore [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#159]
## feat(venue-explore): create a service for venue explore [2]

N/A

## Tasks:

- [ ] Call endpoint with `fromFetch`
- [ ] Get location href with `getLocationHref`
- [ ] Handle success and error cases with: `processFetchResponse` and `processFetchError`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

#156
