### ISSUE TITLE
feat(venue-explore): put data into reducer [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#160]
## feat(venue-explore): put data into reducer

N/A

## Tasks:

- [x] In the `venuesReducer`
- [x] Handle action.type, `EVenuesAction.GET_VENUE_EXPLORE_SUCCESS`
- [x] Store data into `recommendedPlaces`
  - [x] `recommendedPlaces: NRecommendedPLaces.IRecommendedPLaces<NVenue.IVenue>`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

#156
