### ISSUE TITLE
feat(playground): support asynchronous actions success [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#186]
## feat(playground): support asynchronous actions success [2]

support asynchronous actions success

## Tasks:

- [ ] On playground
 - [ ] User can click on `Success` button
   - [ ] Create a `mock` for response
   - [ ] Dispatch `asyncAction.success`, with created mock as `parameter`
- [ ] Create a component `FormAsyncActions`

## Extra materials:

N/A

#### FormAsyncActions

```
interface IProps {
  asyncAction: getVenuesSearchAsync | getVenuesExploreAsync
}
```

## Useful links

- https://storybook.js.org/
- https://tailwindcss.com/docs/

## Related issues

N/A
