### ISSUE TITLE
feat(playground): support asynchronous actions cancel [0,5]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#187]
## feat(playground): support asynchronous actions cancel

support asynchronous actions cancel

## Tasks:

- [x] On playground
  - [x] User can click on `Cancel` button 
  - [x] Dispatch `asyncAction.cancel` with `reason: "Action is cancelled by user"`
  - [x] Use component `FormAsyncActions`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://storybook.js.org/
- https://tailwindcss.com/docs/

## Related issues

#186
