### ISSUE TITLE
feat(playground): support asynchronous actions failure [0,5]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#188]
## feat(playground): support asynchronous actions failure

support asynchronous actions failure

## Tasks:

- [x] On playground
  - [x] User can click on `Failure` button 
  - [x] Dispatch `asyncAction.failure` with `error: "Unknown error"`
  - [x] Use component `FormAsyncActions`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://storybook.js.org/
- https://tailwindcss.com/docs/

## Related issues

#186
