### ISSUE TITLE
feat(venues-trending): add an action for get venues trending [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#189]
## feat(venues-trending): add an action for get venues trending

Returns a list of recommended venues near the current location. For more robust information about the venues themselves (photos/tips/etc.), please see our venue details endpoint.

## Tasks:

- [x] Create an async action `getVenuesTrendingAsync`
  - [x] Create a new interface inside `NRequest`, `TVenuesTrendingPayload`
- [x] Update snapshot of `EVenuesAction`
- [x] Return nothing on `getVenuesTrendingAsync.success`
  - [x] Use `NVenue.IVenue`

## Extra materials:

N/A

### Types

```
<NRequest.TVenuesExplorePayload, NVenue.IVenue[], Error, string>()
```

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

N/A
