### ISSUE TITLE
feat(venue-trending): create an epic venue trending [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#190]
## feat(venue-trending): create an epic venue select

Returns a list of recommended venues near the current location. For more robust information about the venues themselves (photos/tips/etc.), please see our venue details endpoint.

## Tasks:

- [x] Udapte `EApiPathnames`, add endpoint for venue explore
- [x] Create an epic `getVenuesTrendingEpic`
- [x] On success case, dispatch `EVenuesAction.GET_VENUES_TRENDING_SUCCESS`
- [x] On error case, dispatch `EVenuesAction.GET_VENUES_TRENDING_FAILURE`
- [x] On multiple call, dispatch `EVenuesAction.GET_VENUES_TRENDING_CANCEL`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

#189
#191
