### ISSUE TITLE
feat(venue-trending): create a service for venue trending [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#191]
## feat(venue-trending): create a service for venue trending

Returns a list of recommended venues near the current location. For more robust information about the venues themselves (photos/tips/etc.), please see our venue details endpoint.

## Tasks:

- [x] Call endpoint with `fromFetch`
- [x] Get location href with `getLocationHref`
- [x] Handle success and error cases with: `processFetchResponse` and `processFetchError`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/explore

## Related issues

#189
