### ISSUE TITLE
feat(standalone): use package in standalone mode [3H]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#193]
## use package in standalone mode

Timebox of 3 hours

## Tasks:

- [x] For asynchronous action
  - [x] Dispatch request action
  - [x] Wait for success, cancel or failure action
  - [x] Return response
- [x] For synchronous action
  - [x] Dispatch action
  - [x] Return response from state, with a given selector

## Extra materials:

```
- dispatchAsyncAction(asyncAction, selector).then(console.log)
- dispatchSyncAction(action, selector).then(console.log)
```

### Types

N/A

## Useful links

https://medium.com/resolvejs/resolve-redux-backend-ebcfc79bbbea
https://blog.webbylab.com/redux-on-backend/
https://blog.bitsrc.io/can-redux-be-used-on-the-server-e2d3ecbf7ee4

## Related issues

N/A
