### ISSUE TITLE
feat(venues-suggestcompletion): add an action for get venues suggest completion [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#211]
## feat(venues-suggest-completion): add an action for get venues suggest completion

Returns a list of mini-venues partially matching the search term, near the location.

## Tasks:

- [x] Create an async action `getVenuesSuggestCompletionAsync`
  - [x] Create a new interface inside `NRequest`, `TVenuesSuggestCompletionPayload`
- [x] Update snapshot of `EVenuesAction`
- [x] Return nothing on `getVenuesSuggestCompletionAsync.success`
  - [x] Use `NVenue.IMiniVenue`

## Extra materials:

N/A

### Types

```
<NRequest.TVenuesSuggestCompletionPayload, NVenue.IMiniVenue[], Error, string>()
```

## Useful links

- https://developer.foursquare.com/docs/api/venues/suggestcompletion

## Related issues

N/A
