### ISSUE TITLE
feat(venue-suggest-completion): create an epic venue suggest completion [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#212]
## feat(venue-suggest-completion): create an epic venue suggest completion

Returns a list of mini-venues partially matching the search term, near the location.

## Tasks:

- [x] Udapte `EApiPathnames`, add endpoint for venue explore
- [x] Create an epic `getVenuesSuggestCompletionEpic`
- [x] On success case, dispatch `getVenuesSuggestCompletionAsync.success`
- [x] On error case, dispatch `getVenuesSuggestCompletionAsync.failure`
- [x] On multiple call, dispatch `getVenuesSuggestCompletionAsync.cancel`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/suggestcompletion

## Related issues

#211
