### ISSUE TITLE
feat(venue-suggest-completion): create a service for venue suggest completion [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#213]
## feat(venue-suggest-completion): create a service for venue suggest completion

Returns a list of mini-venues partially matching the search term, near the location.

## Tasks:

- [x] Call endpoint with `fromFetch`
- [x] Get location href with `getLocationHref`
- [x] Handle success and error cases with: `processFetchResponse` and `processFetchError`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/suggestcompletion

## Related issues

#211
