### ISSUE TITLE
docs(playground): Update stories with life and venue actions [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#217]
## Title

Description

## Tasks:

- [x] Update story on `putCredentials`
- [x] Update story on `getVenuesSearchAsync`
- [x] Update story on `getVenuesExploreAsync`
- [x] Update story on `getVenuesTrendingAsync`

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

N/A

**Comment by arnaud-zg** [comment]
Stucked
