### ISSUE TITLE
feat(venues-likes): add an action for get venues likes [1] 

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#232]
## feat(venues-likes): add an action for get venues likes

Returns friends and a total count of users who have liked this venue.

## Tasks:

- [x] Create an async action `getVenuesLikesAsync`
  - [x] Create a new interface inside `NRequest`, `TVenuesLikesPayload`
- [x] Update snapshot of `EVenuesAction`
- [x] Return nothing on `getVenuesLikesAsync.success`
  - [x] Use `NLike.IResponse`

## Extra materials:

N/A

### Types

```
<NRequest.TVenuesLikesPayload, NLike.ILikes, Error, string>()
```

## Useful links

- https://developer.foursquare.com/docs/api/venues/likes

## Related issues

N/A
