### ISSUE TITLE
feat(venue-likes): create an epic venue likes [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#233]
## feat(venue-likes): create an epic venue likes

Returns friends and a total count of users who have liked this venue.

## Tasks:

- [ ] Udapte `EApiPathnames`, add endpoint for venue explore
- [ ] Create an epic `getVenuesLikesEpic`
- [ ] On success case, dispatch `getVenuesLikesAsync.success`
- [ ] On error case, dispatch `getVenuesLikesAsync.failure`
- [ ] On multiple call, dispatch `getVenuesLikesAsync.cancel`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/likes

## Related issues

#232
