### ISSUE TITLE
feat(venue-likes): create a service for venue likes [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#234]
## feat(venue-likes): create a service for venue likes

Returns friends and a total count of users who have liked this venue.

## Tasks:

- [x] Call endpoint with `fromFetch`
- [x] Get location href with `getLocationHref`
- [x] Handle success and error cases with: `processFetchResponse` and `processFetchError`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/likes

## Related issues

#232
