### ISSUE TITLE
feat(venue-listed): add get venue listed action, adapter, epics, reducers, selectors and services [1] 

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#291]
## feat(venue-listed): add get venue listed action, adapter, epics, reducers, selectors and services [1] 

Returns the lists that this venue appears on.

## Tasks:

- [x] Create an action `getVenueListedAsync`
  - [ ] Create a namespace `NEntity` which contain a type `TEntity`
```
createAsyncAction(...)<void, NEntity.TEntity[], Error, string>(...)
```
- [x] Create a service `getObservableVenueListed`
  - [x] Call the endpoint with `VENUE_ID`
- [x] Create an adapter `adaptGetVenuesListed`
  - [x] Handle a payload with type `NPayload.IPayload<NVenueLiked.IResponse>`
  - [x] Create a namespace `NVenueLiked` which contain an interface `IResponse`
- [x] Create an epic `getVenueListedEpic`
- [x] Handle `getVenueListedAsync.success` on `venuesReducer`
- [x] Handle `getVenueListedAsync.success` on `statusReducer`
- [x] Create a selector `venueListedSelector`
 - [x] Write unit test

## Extra materials:

N/A

### Types

- `https://developer.foursquare.com/docs/api/venues/listed#response`

## Useful links

- `GET https://api.foursquare.com/v2/venues/VENUE_ID/listed`
https://developer.foursquare.com/docs/api/venues/listed

## Related issues

N/A
