### ISSUE TITLE
feat(list-details): add get list details action, adapter, epics, reducers, selectors and services [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#293]
## feat(list-details): add get list details action, adapter, epics, reducers, selectors and services [1]

Gives details about a list

## Tasks:

- [x] Create an action `getListDetailsAsync`
  - [x] Create a namespace `NListDetails` which contain a type `IListDetails`
```
createAsyncAction(...)<void, NListDetails.IListDetails[], Error, string>(...)
```
- [x] Create a service `getObservableListDetails`
  - [x] Call the endpoint with `LIST_ID`
- [x] Create an adapter `adaptGetListDetails`
  - [x] Handle a payload with type `NPayload.IPayload<NListDetails.IResponse>`
  - [x] Create a namespace `NListDetails` which contain an interface `IResponse`
- [x] Create an epic `getListDetailsEpic`
- [x] Handle `getListDetailsAsync.success` on `listReducer`
  - Create an action list
  - Create a reducer list
- [x] Handle `getListDetailsAsync.success` on `statusReducer`
- [x] Create a selector `listDetailsSelector`
 - [x] Write unit test

## Extra materials:

N/A

### Types

- https://developer.foursquare.com/docs/api/lists/details#response

## Useful links

- https://developer.foursquare.com/docs/api/lists/details

## Related issues

#291
