### ISSUE TITLE
feat(photo-details): add get photos details action, adapter, epics, reducers, selectors and services [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#294]
## feat(photo-details): add get photos details action, adapter, epics, reducers, selectors and services [1]

Get details of a photo

## Tasks:

- [ ] Create an action `getPhotoDetailsAsync`
  - [ ] Create a namespace `NPhotoDetails` which contain a type `IPhotoDetails`
```
createAsyncAction(...)<void, NPhotoDetails.IPhotoDetails[], Error, string>(...)
```
- [ ] Create a service `getObservablePhotoDetails`
  - [ ] Call the endpoint with `PHOTO_ID`
- [ ] Create an adapter `adaptGetPhotoDetails`
  - [ ] Handle a payload with type `NPayload.IPayload<NPhotoDetails.IResponse>`
  - [ ] Create a namespace `NPhotoDetails` which contain an interface `IResponse`
- [ ] Create an epic `getPhotoDetailsEpic`
- [ ] Handle `getPhotoDetailsAsync.success` on `listReducer`
  - Create an action list
  - Create a reducer list
- [ ] Handle `getPhotoDetailsAsync.success` on `statusReducer`
- [ ] Create a selector `photoDetailsSelector`
 - [ ] Write unit test

## Extra materials:

N/A

### Types

- https://developer.foursquare.com/docs/api/photos/details#response

## Useful links

- https://developer.foursquare.com/docs/api/photos/details

## Related issues

N/A
