### ISSUE TITLE
fix(request): save response of each http request [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#295]
## fix(request): save response of each http request [2]

Actually it's not possible to know which request has been executed.

## Tasks:

- [x] Create a new store named `request`
 - [x] Create a namespace `NRequestState`, by default this store will have the action name as key, for example `store.request["PUT_CREDENTIALS"]`.
    - [x] About value it should be like that `{ entityIds: string[] }`

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

N/A
