### ISSUE TITLE
fix(venues): homogenization of venues store [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#296]
## fix(venues): homogenization of venues store [1]

The goal of this issue is to clean venues store.

## Tasks:

- [ ] Every venue should be stored in `entities`
- [ ] `store.venues.nextVenues`, `store.venues.recommendedPlaces`, `store.venues.similarVenues`, `store.venues.trendingEntities` should be useless, it can be removed
  - [ ] Update venue selectors: `venueCategoriesStateSelector`, `venueLocationSelector`, `venuesCategoriesSelector`, `venueSelector`, `venuesEntitiesSelector`, `venuesNextVenuesSelector`, `venuesSimilarSelector`, `venuesRecommendedPlacesSelector`, `venuesSelector`
  - [ ] Selectors should get ids from `store.request`

Nothing to change on `store.venues.categories`

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

#295

**Comment by arnaud-zg** [comment]
There is a high risk to have a conflict it we get the same entity across two actions.
