### ISSUE TITLE
feat(search): add search for venues action [3]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#30]
## Feature: Search for Venues

```
Scenario: As a user, I want to do a search for a venue
Given Jeff type something on the search bar
And he submitted it
Then Jeff should see a list of venues
```

## Tasks:

- [x] Store api keys with `localStorage` for client app
- [x] Store api keys with `node-localStorage` for server app
- [x] Create a util for `Get / Set credentials`
- [x] We can set credentials like that `client.set(config)`

## Extra materials:

We should do a search like that: `getVenuesSearch(payload)`

### Types

```
export const CLIENT_ID_KEY = 'apiClientId'
export const CLIENT_SECRET_KEY = 'apiClientSecret'

export interface ICredentials {
  [CLIENT_ID_KEY]: string
  [CLIENT_SECRET_KEY]: string
}
```

## Useful links

- https://developer.foursquare.com/docs/api/venues/search
- https://www.npmjs.com/package/store

## Related issues

N/A
