### ISSUE TITLE
feat(icon): add helper for icon [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#33]
## Feature: Add helper for icon

```
Scenario: As a user, Jeff want to do a search for a venue
Given Jeff type something on the search bar
And he submitted it
Then Jeff should see a list of venues
And Jeff sees the icons of the associated categories
```

## Tasks:

- [ ] Create a helper for `icon`
- [ ] Create an `enum` for all supported icon size (`32`, `44`, `64`, and `88`)
- [ ] Generate an url for each icon size
- [ ] For each size, generate and url with gray background and without
- [ ] Return an object with size as `key` and url as `value` (`hashmap`)

### Icon

```
Pieces needed to construct category icons at various sizes.
Combine prefix with a size (32, 44, 64, and 88 are available) and suffix,
e.g. https://foursquare.com/img/categories/food/default_64.png.
To get an image with a gray background, use bg_ before the size,
e.g. https://foursquare.com/img/categories_v2/food/icecream_bg_32.png.
```

### Types

```
enum EIconSize {}

interface IIcon {
  prefix: string
  suffix: string
}

interface IIconUrls {
  [EIconSize: string] : string
}

export const getIconUrlList = (icon: IIcon) : IIconUrls => {}
```

## Useful links

- https://developer.foursquare.com/docs/api/venues/categories

## Related issues

- #30
