### ISSUE TITLE
feat(venues-stats): add get venues stats over time action, adapter and services [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#352]
## feat(venues-stats): add get venues stats over time action, adapter and services [2]

Get Your Venue's Stats Over Time

## Tasks:

- [ ] Create an action `getVenuesTimeseries`
  - [ ] Create a namespace `NVenuesTimeseries` which contain a type `IVenuesTimeseries`
- [ ] Create a service `getObservableVenuesTimeseries`
  - [ ] Call the endpoint without any parameter
- [ ] Create an adapter `adaptGetVenuesTimeseries`
  - [ ] Handle a payload with type `NPayload.IPayload<NVenuesTimeseries.IResponse>`
  - [ ] Create a namespace `NVenuesTimeseries` which contain an interface `IResponse`
 - [ ] Write unit test

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/venues/timeseries

## Related issues

N/A
