### ISSUE TITLE
feat(auth): support authenticated endpoint [1]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#353]
## feat(auth): support authenticated endpoint [1]

It is used when you require a Foursquare or Swarm user e.g. to get all the checkins for a given user.

## Tasks:

- [x] Create an action `putAccessToken`
  - [x] This action will accept a parameter with `accessToken`
  - [x] Update `NResolve`, add `IAccessTokenPayload`
  - [x] Update `NLifeState`, add `IAccessToken`
- [x] Create a selector `lifeAccessTokenSelector`
- [x] Handle `putAccessToken` in `lifeReducer`

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://developer.foursquare.com/docs/api/configuration/authentication

## Related issues

N/A
