### ISSUE TITLE
chore: remove redux, redux observable from dependencies [8]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#411]
## Remove redux, redux observable from dependencies

By the time, it seems redux, redux observable is not a very consistent choice for this library. It supposed to be a simple client for the foursquare api.

## Tasks:

- [x] Call an action `myAction(payload, config)`
  - [x] This action will be dispatched to the `observable` method 
  - [x] Fetch API give a `promise`
  - [x] Return a `promise` or an `observable`, depends on `config`

### Element to remove:
- [x] Action
- [x] Reducer
- [x] Epics
- [x] Middleware
- [x] Selector

### Element to keep:
- [x] Adapter
- [x] Constants
- [x] Service
- [x] Utils

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

N/A
