### ISSUE TITLE
feat(search): find a venue with latitude and longitude parameters [3]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#53]
## Feature:  Find a venue with latitude and longitude parameters

```
Scenario: As a user, I want to do a search for a venue
Given Jeff gave my location information (latitude & longitude)
Then Jeff should see a list of venues
```

## Tasks:

- [ ] The endpoint `ENDPOINT: venues/search ` can now accept parameter `PARAMETERS: lat/long = 40.7337621,-74.0095604; intent = checkin`
- [ ] By default if `lat/long` are provided automatically set `intent = checkin` 
- [ ] Create an interface for `requestGetVenuesSearch`'s payload

## Extra materials:

We should do a search like that: `requestGetVenuesSearch({ ll: '40.7099,-73.9622' })`

### Types

```
type TPayload = IGetVenuesSearchByWord | IGetVenuesSearchByLocation

export const requestGetVenuesSearch = (payload = TPayload) =>
  action(EVenuesAction.REQUEST_GET_VENUES_SEARCH, payload)
```

## Useful links

https://developer.foursquare.com/docs/api/venues/search

## Related issues

N/A
