### ISSUE TITLE
feat(search): find a specific place nearby [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#54]
## Feature:  Find a specific place nearby

```
Scenario: As a user, Jeff want to do a search for a venue
Given Jeff type something on the search bar
And he submitted it
Then Jeff should see a list of venues nearby
```

## Tasks:

- [ ] The endpoint `ENDPOINT: venues/search ` can now accept parameter `PARAMETERS: lat/long = 40.7629212,-73.9935085; query = ShopMart; intent = browse; radius = 500`
- [ ] Add a new type in `TPayload`, `IGetVenuesSearchByWordNearby` ?
- [ ] Set a `radius` by default at `500`

## Extra materials:

We should do a search like that: `requestGetVenuesSearch({ ll: '40.7099,-73.9622', query: "Something", intent: "browse", radius: 500 })`

### Types

```
type TPayload = IGetVenuesSearchByWord | IGetVenuesSearchByLocation | IGetVenuesSearchByWordNearby

export const requestGetVenuesSearch = (payload = TPayload) =>
  action(EVenuesAction.REQUEST_GET_VENUES_SEARCH, payload)
```

## Useful links

https://developer.foursquare.com/docs/api/venues/search

## Related issues

N/A
