### ISSUE TITLE
feat(store): add redux store creator with epics [3]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#78]
## feat(store): add redux store creator with epics [3]

```
Scenario: As a user, I want to find a steak house restaurant
Given Jeff type "steak house" on the search bar
And he submitted it
Then Jeff should see a list of venues related to "steak house"
```

## Tasks:

- [x] Create a function named `configureStore()`
  - [x] Combine all available `reducers` into `store`
  - [x] Inject middlware with all `epics`

## Extra materials:

We should have access to `configureStore`, example: `import { configureStore } from 'ts-foursquare'`

### Types

N/A

## Useful links

https://redux.js.org/api/createstore
https://redux.js.org/api/combinereducers
https://redux-observable.js.org/docs/basics/SettingUpTheMiddleware.html

## Related issues

N/A
