### ISSUE TITLE
feat(playground): add search venues search in demo mode [2]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#79]
## feat(playground): add search venues search in demo mode

```
Scenario: As a user, I want to find a steak house restaurant
Given Jeff type "steak house" on the search bar
And he submitted it
Then Jeff should see a list of venues related to "steak house"
```

## Tasks:

- [x] Create a story
- [x] Create a container `VenuesSearchContainer`
- [x] Create a component `VenuesSearch`, which is connected to `VenuesSearchContainer`
- [x] Use `mapDispatchToProps` and add `requestGetVenuesSearch` 
- [x] Render `venues.entities` in `VenuesSearch`

## Extra materials:

N/A

### Types

N/A

## Useful links

N/A

## Related issues

N/A
