### ISSUE TITLE
feat(playground): add credentials in demo mode [2] 

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#80]
## feat(playground): add credentials in demo mode

```
Scenario: As a user, I want to find a steak house restaurant
Given Jeff type "steak house" on the search bar
And he submitted it
Then Jeff should see a list of venues related to "steak house"
```

## Tasks:

- [x] Create a story
- [x] Create a container `LifeContainer`
- [x] Create a component `Life`, which is connected to `LifeContainer`
- [x] Dispatch `putCredentials` when user click on button
- [x] Render `life.status` in `LifeContainer`

## Extra materials:

| `status` | `color` |
| - | - |
| `false` | `red` |
| `true` | `green` |

### Types

N/A

## Useful links

N/A

## Related issues

N/A
