### ISSUE TITLE
chore(template): add template for issues and pull requests [0,5]

### ISSUE THREAD

**Issue by arnaud-zg** [arnaud-zg/ts-foursquare#87]
## chore(template): add template for issues and pull requests

Create an issue or pull request with template

## Tasks:

- [x] Create a folder `.github`
- [x] Add template for issues
- [x] Add template for pull requests

## Extra materials:

N/A

### Types

N/A

## Useful links

- https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

## Related issues

N/A
